/*
    See a thorouhly commented linker file here:
    https://github.com/wntrblm/Castor_and_Pollux/blob/main/firmware/scripts/samd21g18a.ld
*/

ENTRY(AGON_START)

/*
    AGON_RAM_START and AGON_RAM_SIZE need to be set previously
*/

MEMORY {
    USERRAM (rw) : ORIGIN = AGON_RAM_START, LENGTH = AGON_RAM_SIZE  /* Define RAM region */
}

SECTIONS
{
    . = AGON_RAM_START;

    .init : { *(.init) } > USERRAM

    .text : { *(.text) } > USERRAM

    .rodata : { *(.rodata) } > USERRAM

    .data : { *(.data) } > USERRAM

}

__stack  = AGON_RAM_START + AGON_RAM_SIZE;

/* BBC Basic symbols that cannot be computed by gnu-as before linkage */
RAM_SIZE = RAM_END - RAM_START - 1;
