RAM_START = 0x40000;                                      /* MOS load address */
STACKTOP  = 0xB0000;                                      /* Start of MOSLET memory area */
RAM_SIZE  = STACKTOP - RAM_START;

ENTRY(AGON_START)

MEMORY {
    USERRAM (rw) : ORIGIN = RAM_START, LENGTH = RAM_SIZE  /* Define RAM region */
}

SECTIONS {
    . = RAM_START;

    .init : { *(.init) } > USERRAM

    .text : { *(.text) } > USERRAM

    .data : { *(.data) } > USERRAM

    .bss (NOLOAD): {
        bss_start = .;
        *(.bss-1st)
        *(.bss)
        *(.bss-end)
        bss_end = .;
    } > USERRAM
}

bss_size = SIZEOF(.bss);
